
def map_partner_value(partner_code):
                    partner_mapping = {
    "aucvl": "AUC Venture Lab",
    "elriada": "El-Riada Association",
    "gwla": "Giving Without Limits Association",
    "lmf": "Life Makers Foundation",
    "career180": "Career 180 & Icareer",
    "holol": "Holol Group",
    "super_fny": "SuperFny",
    "botton_up": "ButtonUp",
    "entlaq": "Entlaq",
    "aast": "Arab Academy for Science, Technology and Maritime Transport",
    "ice": "ICE Alex",
    "athar": "Athar",
    "aa_j": "ActionAid Arab Region",
    "dtda_j": "Danish Trade Union Development Agency (DTDA)",
    "for9a": "For9a",
    "game_j": "GAME",
    "jyif": "Jordan Youth Innovation Forum (JYIF)",
    "liwan": "Liwan Youth Space",
    "pie":"Plan International Egypt",
    "pij": "Plan International Jordan",
    "bpwa": "Business and Professional Women Association (BPWA)",
    "sds": "SDS",
    "gfjtu": "The General Federation of Jordanian Trade Unions (GFJTU)",
    "ywca": "The Young Women Christian Association (YWCA)",
    "tt_j": "Turning Tables Jordan",
    "apls": "Alianza por la Solidaridad",
    "chifae": "Association Chifae",
    "unfm": "Association Union Nationale des Femmes du Maroc (UNFM)",
    "aqj": "Association Qualification des Jeunes (AQJ)",
    "dtda_m": "Danish Trade Union Development Agency (DTDA)",
    "esmaroc": "Entreprises Sociales Maroc (ES Maroc)",
    "lhjoyeuse": "L'Heure Joyeuse",
    "maje": "Marock Jeunes",
    "swiss": "Swiss Contact",
    "tt_m": "Turning Tables",
    "mepo": "Um Mami / Melting Pot",
    "umt": "Union Marocaine du Travail (UMT)",
    "aa_t": "ActionAid Arab Region",
    "drc": "Danish Refugee Council (DRC)",
    "dtda_t": "Danish Trade Union Development Agency (DTDA)",
    "efe": "Education for Employment Tunisia (EfE)",
    "elspace": "El Space",
    "game_t": "GAME",
    "idebate": "IDebate",
    "impa": "Impact Partner",
    "injaz": "Injaz",
    "mou": "Moughayroun/Change Makers",
    "tffd": "The Tunisian Foundation for Development (TFFD)",
    "ugtt": "Union Générale Tunisienne du Travail (UGTT)",
    "weyouth": "WeYouth",
    }
                    return partner_mapping.get(partner_code, "")

def map_gender_value(gender_code):
                    gender_mapping = {
        "1": "Male",
        "2": "Female",
        "3": "Prefer not to say",
    }
                    return gender_mapping.get(gender_code, "")

def map_region_value(region_code):
                    region_mapping = {
        "alex": "Alexandria",
        "assi": "Assiut",
        "cair": "Cairo",
        "cair2": "Qalyubia",
        "cair3": "Giza",
        "bah": "Al-bahera",
        "ajlo": "Ajloun",
        "amma": "Amman",
        "aqab": "Aqaba",
        "balq": "Balqa",
        "irbi": "Irbid",
        "jera": "Jerash",
        "kara": "Karak",
        "maan": "Ma'an",
        "mada": "Madaba",
        "mafr": "Mafraq",
        "tafi": "Tafileh",
        "zarq": "Zarqa",
        "beni": "Beni Mellal-Khenifra",
        "casa": "Casablanca-Settat",
        "dakh": "Dakhla-Oued Eddahab",
        "draa": "Drâa-Tafilalet",
        "fesm": "Fès-Meknès",
        "guel": "Guelmim-Oued Noun",
        "laay": "Laâyoune-Sakia Al Hamra",
        "lori": "L'oriental",
        "marr": "Marrakech - Safi",
        "raba": "Rabat - Sale - Kenitra",
        "soum": "Souss-Massa",
        "tang": "Tanger-Tetouan- Al Hoceima",
        "aria": "Ariana",
        "beja": "Beja",
        "bena": "Ben Arous",
        "bize": "Bizert",
        "gabe": "Gabes",
        "gafs": "Gafsa",
        "jend": "Jendouba",
        "kair": "Kairouan",
        "kass": "Kasserine",
        "kebi": "Kebili",
        "leke": "Le Kef",
        "mahd": "Mahdia",
        "mano": "Manouba",
        "mede": "Medenine",
        "moun": "Mounastir",
        "nebe": "Nabeul",
        "sfax": "Sfax",
        "sidi": "Sidi Bouzid",
        "sili": "Siliana",
        "sous": "Sousse",
        "tata": "Tataouine",
        "toze": "Tozeur",
        "tuni": "Tunis",
        "zagh": "Zaghouan",
    }
                    return region_mapping.get(region_code, "")

def map_enum_value(value):
                        enum_mapping = {
                        "1": "Enumerator",
                        "2": "Myself"
                        }
                        return enum_mapping.get(value, "")

                # Function to map country values
def map_country_value(country_code):
                    country_mapping = {
                        "1": "Egypt",
                        "2": "Jordan",
                        "3": "Morocco",
                        "4": "Tunisia",
                    }
                    return country_mapping.get(country_code, "")

def map_district_value(district_code):
                    district_mapping = {
                        "cair1": "Abbassia",
                        "cair2": "Ain Shams",
                        "cair3": "Al Asmarat",
                        "cair4": "Azbakeya",
                        "cair5": "Bab al-Louq",
                        "cair6": "Boulaq",
                        "cair7": "Daher",
                        "cair8": "Downtown Cairo",
                        "cair9": "El Manial",
                        "cair10": "El Marg",
                        "cair11": "El Matareya",
                        "cair12": "El Qobbah",
                        "cair13": "El Rehab",
                        "cair14": "El Sahel",
                        "cair15": "El Sakkakini",
                        "cair16": "Ezbet El Haggana",
                        "cair17": "Ezbet El Nakhl",
                        "cair18": "Faggala",
                        "cair19": "Fifth Settlement",
                        "cair20": "Fustat",
                        "cair21": "Garden City",
                        "cair22": "Gezira",
                        "cair23": "Heliopolis, Cairo",
                        "cair24": "Maadi",
                        "cair25": "Roda Island",
                        "cair26": "Shubra",
                        "cair27": "Shubra El Kheima",
                        "cair28": "Zeitoun, Cairo",
                        # Add more mappings as needed
                    }
                    return district_mapping.get(district_code, "")
                # Function to map district values
def map_training_value(training_code):
                    training_mapping = {
                      "el1": "Life Skills",
        "el2": "Ready for Work",
        "el3": "Enterprise Your Life",
        "gwla1": "Life Skills",
        "gwla2": "Ready for Work",
        "gwla3": "Enterprise Your Life",
        "lmf1": "Life Skills",
        "lmf2": "Ready for Work",
        "lmf3": "Enterprise Your Life",
        "liwan_ls_1": "Self-development",
        "liwan_ls_2": "Communication",
        "liwan_ls_3": "Ethics and code of conduct",
        "liwan_ls_4": "Team work",
        "liwan_ls_5": "Mindset",
        "liwan_ls_6": "Leadership",
        "game_ls_1": "GAME Zones Weekly Practices",
        "game_ls_2": "GAME KIT Trainings",
        "game_t_1": "Technical Skills Trainings",
        "jyif_ls_1": "GAME Zones Weekly Practices",
        "jyif_ls_2": "GAME KIT Trainings",
        "jyif_t_1": "Technical Skills Trainings",
        "rob_t_1": "STEM trainer - Robotics",
        "rob_t_2": "STEM trainer - AI",
        "rob_t_3": "STEM trainer - Mental Math",
        "rob_t_4": "Full Skills Graphic Design",
        "rob_t_5": "Advanced website developer",
        "rob_t_6": "Workshops /CV building",
        "rob_t_7": "Workshops /Work on freelancing platforms",
        "ywca_t_1": "Mosaic Training",
        "ywca_t_2": "House Keeping Training",
        "ywca_t_3": "Cleaning Facility Training",
        "tt_j_t_1": "Content Creation Essentials",
        "liwan_t_1": "LinkedIn",
        "liwan_t_2": "Microsoft Office (PPT - Excel - Word)",
        "liwan_t_3": "Film production",
        "liwan_t_4": "Art of Act",
        "liwan_t_5": "Recycling",
        "liwan_t_6": "Fashion",
        "sds_t_1": "RPA Traning Plan first session",
        "sds_t_2": "RPA Traning Plan second session",
        "for9a_e": "Entrepreneurship/Business Development Counseling Sessions",
        "for9a_e": "Local Artisans Product Development Training",
        "tt_j_e": "Journey to Entrepreneurial Success",
        "pij_e": "Entrepreneurship skills and Business Plan Development",
        "chifaels": "Soft Skills (Self-esteem, Self-confidence, Assertiveness, Decision Making, Problem solving, Adaptability, Communication and stress management, Team work, Conflict management, Creation of a personal project)",
        "unfmls": "Soft Skills (Self-esteem, Self-confidence, Assertiveness, Decision Making, Problem solving, Adaptability, Communication and stress management, Team work, Conflict management, Creation of a personal project)",
        "esmarocls": "Soft Skills (Self-esteem, Self-confidence, Assertiveness, Decision Making, Problem solving, Adaptability, Communication and stress management, Team work, Conflict management, Creation of a personal project)",
        "chifae_t1": "Catering",
        "chifae_t2": "Cabling/automotive",
        "chifae_t3": "Industrial frabrication",
        "unfm_t1": "Pharmacy assistant",
        "unfm_t2": "Nursery assistant",
        "unfm_t3": "Cutting and sewing specialist",
        "unfm_t4": "Hairdresser and beautician",
        "unfm_t5": "Kitchen assistant",
        "unfm_t6": "Camera technician",
        "unfm_t7": "Computing and office automation",
        "unfm_t8": "Care assistant",
        "esmaroc_t1": "Restauration and service",
        "esmaroc_t2": "Infographics",
        "esmaroc_t3": "Contability and gestion",
        "esmaroc_t4": "Hairdresser and beautician",
        "mepo_t_1": "Culinary Training",
        "tt_m_t1": "Graphic Design",
        "tt_m_t2": "Video",
        "tt_m_t3": "Photography",
        "tt_m_t4": "Audio Techniques",
        "chifae_e_1": "Raising awareness and initiation to entrepreneurship",
        "chifae_e_3": "Business plan training and support",
        "aqj_e_1": "Raising awareness and initiation to entrepreneurship",
        "aqj_e_3": "Business plan training and support",
        "esmaroc_e_1": "Raising awareness and initiation to entrepreneurship",
        "esmaroc_e_3": "Business plan training and support",
        "lhjoyeuse_e_1": "Raising awareness and initiation to entrepreneurship",
        "lhjoyeuse_e_3": "Business plan training and support",
        "mepo_e_1": "Innovation Bootcamp/Hospitality",
        "mepo_e_2": "Innovation Bootcamp/Food Tech",
        "iiDebate_ls1": "Community & Family Dialogue Session - iiDebate",
        "iiDebate_ls2": "Youth Career Guides - iiDebate",
        "iiDebate_ls3": "Soft Skills Workshop - iiDebate",
        "iiDebate_ls4": "Mobile Zone - iiDebate",
        "mou_ls1": "Community & Family Dialogue Session - Moughayrun",
        "mou_ls2": "Youth Career Guides - Moughayrun",
        "mou_ls3": "Soft Skills Workshop - Moughayrun",
        "mou_ls4": "Mobile Zone - Moughayrun",
        "game_t_ls_1": "GAME Finals",
        "game_t_ls_2": "Life skills through street sport cycle",
        "game_t_ls_3": "Playmaker Camp",
        "game_t_ls_4": "Advanced Playmakers (Hall of GAME) ToT",
        "iiDebate_t_1": "ToT for youth facilitators - iiDebate",
        "mou_t_1": "ToT for youth Peer Educators - Moughayrun",
        "elspace_t_1": "Technical skills training - 2D DESIGN & LASER Cutting",
        "elspace_t_2": "Technical skills training - 3D design and printing techniques",
        "elspace_t_3": "Technical skills training - Data Analysis",
        "elspace_t_4": "Technical skills training - Digital Marketing",
        "elspace_t_5": "Technical skills training - CNC MACHINING",
        "elspace_t_6": "Technical skills training - Computer Skills And Bookkeeping",
        "elspace_t_7": "Technical skills training - Iot And Electronics",
        "elspace_t_8": "Technical skills training - UX/UI design",
        "weyouth_ls_1": "Facilitation Techniques",
        "weyouth_ls_2": "Facilitation Techniques and Evaluation",
        "weyouth_ls_3": "CV, Motivation Letter, and E-mail Writing",
        "weyouth_ls_4": "Job Interview Preparation and Job Hunting",
        "weyouth_ls_5": "Public Speaking",
        "weyouth_t_1": "UX/UI Design",
        "weyouth_t_2": "Digital Marketing",
        "weyouth_t_3": "Data Analysis",
        "weyouth_t_4": "Photovoltaic: Energy efficiency",
        "weyouth_t_5": "Quality, health, safety, and environment",
        "efe": "Entrepreneurial training",
        "impa_e": "Entrepreneurial training",
        "injaz_e": "Entrepreneurial training",
        "tffd_e": "Entrepreneurial training"
                    }
                    return training_mapping.get(training_code, "")
                
                
def map_whatsapp_value(value):
                    whatsapp_mapping = {
                    "1": "Yes_WA",
                    "0": "No_WA",
                    "2": "I don't have WhatsApp",
                }
                    return whatsapp_mapping.get(value, "")

